//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthRPCConfig) DeepCopyInto(out *AuthRPCConfig) {
	*out = *in
	if in.APIs != nil {
		in, out := &in.APIs, &out.APIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthRPCConfig.
func (in *AuthRPCConfig) DeepCopy() *AuthRPCConfig {
	if in == nil {
		return nil
	}
	out := new(AuthRPCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchSubmissionInfo) DeepCopyInto(out *BatchSubmissionInfo) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchSubmissionInfo.
func (in *BatchSubmissionInfo) DeepCopy() *BatchSubmissionInfo {
	if in == nil {
		return nil
	}
	out := new(BatchSubmissionInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatcherInfo) DeepCopyInto(out *BatcherInfo) {
	*out = *in
	if in.LastBatchSubmitted != nil {
		in, out := &in.LastBatchSubmitted, &out.LastBatchSubmitted
		*out = new(BatchSubmissionInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatcherInfo.
func (in *BatcherInfo) DeepCopy() *BatcherInfo {
	if in == nil {
		return nil
	}
	out := new(BatcherInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BatchingConfig) DeepCopyInto(out *BatchingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BatchingConfig.
func (in *BatchingConfig) DeepCopy() *BatchingConfig {
	if in == nil {
		return nil
	}
	out := new(BatchingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CORSConfig) DeepCopyInto(out *CORSConfig) {
	*out = *in
	if in.Origins != nil {
		in, out := &in.Origins, &out.Origins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Methods != nil {
		in, out := &in.Methods, &out.Methods
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CORSConfig.
func (in *CORSConfig) DeepCopy() *CORSConfig {
	if in == nil {
		return nil
	}
	out := new(CORSConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChainHeadInfo) DeepCopyInto(out *ChainHeadInfo) {
	*out = *in
	in.Timestamp.DeepCopyInto(&out.Timestamp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChainHeadInfo.
func (in *ChainHeadInfo) DeepCopy() *ChainHeadInfo {
	if in == nil {
		return nil
	}
	out := new(ChainHeadInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigSource) DeepCopyInto(out *ConfigSource) {
	*out = *in
	if in.ConfigMapRef != nil {
		in, out := &in.ConfigMapRef, &out.ConfigMapRef
		*out = new(v1.ConfigMapKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigSource.
func (in *ConfigSource) DeepCopy() *ConfigSource {
	if in == nil {
		return nil
	}
	out := new(ConfigSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ContractAddressConfig) DeepCopyInto(out *ContractAddressConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ContractAddressConfig.
func (in *ContractAddressConfig) DeepCopy() *ContractAddressConfig {
	if in == nil {
		return nil
	}
	out := new(ContractAddressConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DataAvailabilityConfig) DeepCopyInto(out *DataAvailabilityConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DataAvailabilityConfig.
func (in *DataAvailabilityConfig) DeepCopy() *DataAvailabilityConfig {
	if in == nil {
		return nil
	}
	out := new(DataAvailabilityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EngineConfig) DeepCopyInto(out *EngineConfig) {
	*out = *in
	if in.JWTSecret != nil {
		in, out := &in.JWTSecret, &out.JWTSecret
		*out = new(SecretKeyRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EngineConfig.
func (in *EngineConfig) DeepCopy() *EngineConfig {
	if in == nil {
		return nil
	}
	out := new(EngineConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GethNetworkingConfig) DeepCopyInto(out *GethNetworkingConfig) {
	*out = *in
	if in.HTTP != nil {
		in, out := &in.HTTP, &out.HTTP
		*out = new(HTTPConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.WS != nil {
		in, out := &in.WS, &out.WS
		*out = new(WSConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.AuthRPC != nil {
		in, out := &in.AuthRPC, &out.AuthRPC
		*out = new(AuthRPCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.P2P != nil {
		in, out := &in.P2P, &out.P2P
		*out = new(GethP2PConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GethNetworkingConfig.
func (in *GethNetworkingConfig) DeepCopy() *GethNetworkingConfig {
	if in == nil {
		return nil
	}
	out := new(GethNetworkingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GethP2PConfig) DeepCopyInto(out *GethP2PConfig) {
	*out = *in
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GethP2PConfig.
func (in *GethP2PConfig) DeepCopy() *GethP2PConfig {
	if in == nil {
		return nil
	}
	out := new(GethP2PConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPConfig) DeepCopyInto(out *HTTPConfig) {
	*out = *in
	if in.APIs != nil {
		in, out := &in.APIs, &out.APIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.CORS != nil {
		in, out := &in.CORS, &out.CORS
		*out = new(CORSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPConfig.
func (in *HTTPConfig) DeepCopy() *HTTPConfig {
	if in == nil {
		return nil
	}
	out := new(HTTPConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *L1TransactionConfig) DeepCopyInto(out *L1TransactionConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new L1TransactionConfig.
func (in *L1TransactionConfig) DeepCopy() *L1TransactionConfig {
	if in == nil {
		return nil
	}
	out := new(L1TransactionConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingConfig) DeepCopyInto(out *LoggingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingConfig.
func (in *LoggingConfig) DeepCopy() *LoggingConfig {
	if in == nil {
		return nil
	}
	out := new(LoggingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsConfig) DeepCopyInto(out *MetricsConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsConfig.
func (in *MetricsConfig) DeepCopy() *MetricsConfig {
	if in == nil {
		return nil
	}
	out := new(MetricsConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkContractAddresses) DeepCopyInto(out *NetworkContractAddresses) {
	*out = *in
	in.LastDiscoveryTime.DeepCopyInto(&out.LastDiscoveryTime)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkContractAddresses.
func (in *NetworkContractAddresses) DeepCopy() *NetworkContractAddresses {
	if in == nil {
		return nil
	}
	out := new(NetworkContractAddresses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NetworkInfo) DeepCopyInto(out *NetworkInfo) {
	*out = *in
	in.DeploymentTimestamp.DeepCopyInto(&out.DeploymentTimestamp)
	in.LastUpdated.DeepCopyInto(&out.LastUpdated)
	if in.DiscoveredContracts != nil {
		in, out := &in.DiscoveredContracts, &out.DiscoveredContracts
		*out = new(NetworkContractAddresses)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NetworkInfo.
func (in *NetworkInfo) DeepCopy() *NetworkInfo {
	if in == nil {
		return nil
	}
	out := new(NetworkInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeInfo) DeepCopyInto(out *NodeInfo) {
	*out = *in
	if in.ChainHead != nil {
		in, out := &in.ChainHead, &out.ChainHead
		*out = new(ChainHeadInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.SyncStatus != nil {
		in, out := &in.SyncStatus, &out.SyncStatus
		*out = new(SyncStatusInfo)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeInfo.
func (in *NodeInfo) DeepCopy() *NodeInfo {
	if in == nil {
		return nil
	}
	out := new(NodeInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpBatcher) DeepCopyInto(out *OpBatcher) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpBatcher.
func (in *OpBatcher) DeepCopy() *OpBatcher {
	if in == nil {
		return nil
	}
	out := new(OpBatcher)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpBatcher) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpBatcherList) DeepCopyInto(out *OpBatcherList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpBatcher, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpBatcherList.
func (in *OpBatcherList) DeepCopy() *OpBatcherList {
	if in == nil {
		return nil
	}
	out := new(OpBatcherList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpBatcherList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpBatcherSpec) DeepCopyInto(out *OpBatcherSpec) {
	*out = *in
	out.OptimismNetworkRef = in.OptimismNetworkRef
	if in.SequencerRef != nil {
		in, out := &in.SequencerRef, &out.SequencerRef
		*out = new(SequencerReference)
		**out = **in
	}
	in.PrivateKey.DeepCopyInto(&out.PrivateKey)
	if in.Batching != nil {
		in, out := &in.Batching, &out.Batching
		*out = new(BatchingConfig)
		**out = **in
	}
	if in.DataAvailability != nil {
		in, out := &in.DataAvailability, &out.DataAvailability
		*out = new(DataAvailabilityConfig)
		**out = **in
	}
	if in.Throttling != nil {
		in, out := &in.Throttling, &out.Throttling
		*out = new(ThrottlingConfig)
		**out = **in
	}
	if in.L1Transaction != nil {
		in, out := &in.L1Transaction, &out.L1Transaction
		*out = new(L1TransactionConfig)
		**out = **in
	}
	if in.RPC != nil {
		in, out := &in.RPC, &out.RPC
		*out = new(RPCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsConfig)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpBatcherSpec.
func (in *OpBatcherSpec) DeepCopy() *OpBatcherSpec {
	if in == nil {
		return nil
	}
	out := new(OpBatcherSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpBatcherStatus) DeepCopyInto(out *OpBatcherStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.BatcherInfo != nil {
		in, out := &in.BatcherInfo, &out.BatcherInfo
		*out = new(BatcherInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpBatcherStatus.
func (in *OpBatcherStatus) DeepCopy() *OpBatcherStatus {
	if in == nil {
		return nil
	}
	out := new(OpBatcherStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpChallenger) DeepCopyInto(out *OpChallenger) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpChallenger.
func (in *OpChallenger) DeepCopy() *OpChallenger {
	if in == nil {
		return nil
	}
	out := new(OpChallenger)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpChallenger) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpChallengerList) DeepCopyInto(out *OpChallengerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpChallenger, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpChallengerList.
func (in *OpChallengerList) DeepCopy() *OpChallengerList {
	if in == nil {
		return nil
	}
	out := new(OpChallengerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpChallengerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpChallengerSpec) DeepCopyInto(out *OpChallengerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpChallengerSpec.
func (in *OpChallengerSpec) DeepCopy() *OpChallengerSpec {
	if in == nil {
		return nil
	}
	out := new(OpChallengerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpChallengerStatus) DeepCopyInto(out *OpChallengerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpChallengerStatus.
func (in *OpChallengerStatus) DeepCopy() *OpChallengerStatus {
	if in == nil {
		return nil
	}
	out := new(OpChallengerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpGethConfig) DeepCopyInto(out *OpGethConfig) {
	*out = *in
	if in.Storage != nil {
		in, out := &in.Storage, &out.Storage
		*out = new(StorageConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Networking != nil {
		in, out := &in.Networking, &out.Networking
		*out = new(GethNetworkingConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.TxPool != nil {
		in, out := &in.TxPool, &out.TxPool
		*out = new(TxPoolConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Rollup != nil {
		in, out := &in.Rollup, &out.Rollup
		*out = new(RollupConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpGethConfig.
func (in *OpGethConfig) DeepCopy() *OpGethConfig {
	if in == nil {
		return nil
	}
	out := new(OpGethConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpNode) DeepCopyInto(out *OpNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpNode.
func (in *OpNode) DeepCopy() *OpNode {
	if in == nil {
		return nil
	}
	out := new(OpNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpNodeConfig) DeepCopyInto(out *OpNodeConfig) {
	*out = *in
	if in.P2P != nil {
		in, out := &in.P2P, &out.P2P
		*out = new(P2PConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.RPC != nil {
		in, out := &in.RPC, &out.RPC
		*out = new(RPCConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Sequencer != nil {
		in, out := &in.Sequencer, &out.Sequencer
		*out = new(SequencerConfig)
		**out = **in
	}
	if in.Engine != nil {
		in, out := &in.Engine, &out.Engine
		*out = new(EngineConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpNodeConfig.
func (in *OpNodeConfig) DeepCopy() *OpNodeConfig {
	if in == nil {
		return nil
	}
	out := new(OpNodeConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpNodeList) DeepCopyInto(out *OpNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpNodeList.
func (in *OpNodeList) DeepCopy() *OpNodeList {
	if in == nil {
		return nil
	}
	out := new(OpNodeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpNodeResources) DeepCopyInto(out *OpNodeResources) {
	*out = *in
	if in.OpNode != nil {
		in, out := &in.OpNode, &out.OpNode
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
	if in.OpGeth != nil {
		in, out := &in.OpGeth, &out.OpGeth
		*out = new(v1.ResourceRequirements)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpNodeResources.
func (in *OpNodeResources) DeepCopy() *OpNodeResources {
	if in == nil {
		return nil
	}
	out := new(OpNodeResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpNodeSpec) DeepCopyInto(out *OpNodeSpec) {
	*out = *in
	out.OptimismNetworkRef = in.OptimismNetworkRef
	if in.SequencerRef != nil {
		in, out := &in.SequencerRef, &out.SequencerRef
		*out = new(SequencerReference)
		**out = **in
	}
	in.OpNode.DeepCopyInto(&out.OpNode)
	in.OpGeth.DeepCopyInto(&out.OpGeth)
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(OpNodeResources)
		(*in).DeepCopyInto(*out)
	}
	if in.Service != nil {
		in, out := &in.Service, &out.Service
		*out = new(ServiceConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpNodeSpec.
func (in *OpNodeSpec) DeepCopy() *OpNodeSpec {
	if in == nil {
		return nil
	}
	out := new(OpNodeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpNodeStatus) DeepCopyInto(out *OpNodeStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeInfo != nil {
		in, out := &in.NodeInfo, &out.NodeInfo
		*out = new(NodeInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpNodeStatus.
func (in *OpNodeStatus) DeepCopy() *OpNodeStatus {
	if in == nil {
		return nil
	}
	out := new(OpNodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpProposer) DeepCopyInto(out *OpProposer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpProposer.
func (in *OpProposer) DeepCopy() *OpProposer {
	if in == nil {
		return nil
	}
	out := new(OpProposer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpProposer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpProposerList) DeepCopyInto(out *OpProposerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OpProposer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpProposerList.
func (in *OpProposerList) DeepCopy() *OpProposerList {
	if in == nil {
		return nil
	}
	out := new(OpProposerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OpProposerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpProposerSpec) DeepCopyInto(out *OpProposerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpProposerSpec.
func (in *OpProposerSpec) DeepCopy() *OpProposerSpec {
	if in == nil {
		return nil
	}
	out := new(OpProposerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpProposerStatus) DeepCopyInto(out *OpProposerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpProposerStatus.
func (in *OpProposerStatus) DeepCopy() *OpProposerStatus {
	if in == nil {
		return nil
	}
	out := new(OpProposerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimismNetwork) DeepCopyInto(out *OptimismNetwork) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimismNetwork.
func (in *OptimismNetwork) DeepCopy() *OptimismNetwork {
	if in == nil {
		return nil
	}
	out := new(OptimismNetwork)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OptimismNetwork) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimismNetworkList) DeepCopyInto(out *OptimismNetworkList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OptimismNetwork, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimismNetworkList.
func (in *OptimismNetworkList) DeepCopy() *OptimismNetworkList {
	if in == nil {
		return nil
	}
	out := new(OptimismNetworkList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OptimismNetworkList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimismNetworkRef) DeepCopyInto(out *OptimismNetworkRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimismNetworkRef.
func (in *OptimismNetworkRef) DeepCopy() *OptimismNetworkRef {
	if in == nil {
		return nil
	}
	out := new(OptimismNetworkRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimismNetworkSpec) DeepCopyInto(out *OptimismNetworkSpec) {
	*out = *in
	if in.RollupConfig != nil {
		in, out := &in.RollupConfig, &out.RollupConfig
		*out = new(ConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.L2Genesis != nil {
		in, out := &in.L2Genesis, &out.L2Genesis
		*out = new(ConfigSource)
		(*in).DeepCopyInto(*out)
	}
	if in.ContractAddresses != nil {
		in, out := &in.ContractAddresses, &out.ContractAddresses
		*out = new(ContractAddressConfig)
		**out = **in
	}
	if in.SharedConfig != nil {
		in, out := &in.SharedConfig, &out.SharedConfig
		*out = new(SharedConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimismNetworkSpec.
func (in *OptimismNetworkSpec) DeepCopy() *OptimismNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(OptimismNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptimismNetworkStatus) DeepCopyInto(out *OptimismNetworkStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NetworkInfo != nil {
		in, out := &in.NetworkInfo, &out.NetworkInfo
		*out = new(NetworkInfo)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptimismNetworkStatus.
func (in *OptimismNetworkStatus) DeepCopy() *OptimismNetworkStatus {
	if in == nil {
		return nil
	}
	out := new(OptimismNetworkStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2PConfig) DeepCopyInto(out *P2PConfig) {
	*out = *in
	if in.Discovery != nil {
		in, out := &in.Discovery, &out.Discovery
		*out = new(P2PDiscoveryConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Static != nil {
		in, out := &in.Static, &out.Static
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.PeerScoring != nil {
		in, out := &in.PeerScoring, &out.PeerScoring
		*out = new(P2PScoringConfig)
		**out = **in
	}
	if in.PrivateKey != nil {
		in, out := &in.PrivateKey, &out.PrivateKey
		*out = new(SecretKeyRef)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2PConfig.
func (in *P2PConfig) DeepCopy() *P2PConfig {
	if in == nil {
		return nil
	}
	out := new(P2PConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2PDiscoveryConfig) DeepCopyInto(out *P2PDiscoveryConfig) {
	*out = *in
	if in.Bootnodes != nil {
		in, out := &in.Bootnodes, &out.Bootnodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2PDiscoveryConfig.
func (in *P2PDiscoveryConfig) DeepCopy() *P2PDiscoveryConfig {
	if in == nil {
		return nil
	}
	out := new(P2PDiscoveryConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *P2PScoringConfig) DeepCopyInto(out *P2PScoringConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new P2PScoringConfig.
func (in *P2PScoringConfig) DeepCopy() *P2PScoringConfig {
	if in == nil {
		return nil
	}
	out := new(P2PScoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RPCConfig) DeepCopyInto(out *RPCConfig) {
	*out = *in
	if in.CORS != nil {
		in, out := &in.CORS, &out.CORS
		*out = new(CORSConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RPCConfig.
func (in *RPCConfig) DeepCopy() *RPCConfig {
	if in == nil {
		return nil
	}
	out := new(RPCConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceConfig) DeepCopyInto(out *ResourceConfig) {
	*out = *in
	if in.Requests != nil {
		in, out := &in.Requests, &out.Requests
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
	if in.Limits != nil {
		in, out := &in.Limits, &out.Limits
		*out = make(v1.ResourceList, len(*in))
		for key, val := range *in {
			(*out)[key] = val.DeepCopy()
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceConfig.
func (in *ResourceConfig) DeepCopy() *ResourceConfig {
	if in == nil {
		return nil
	}
	out := new(ResourceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RollupConfig) DeepCopyInto(out *RollupConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RollupConfig.
func (in *RollupConfig) DeepCopy() *RollupConfig {
	if in == nil {
		return nil
	}
	out := new(RollupConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeyRef) DeepCopyInto(out *SecretKeyRef) {
	*out = *in
	if in.SecretRef != nil {
		in, out := &in.SecretRef, &out.SecretRef
		*out = new(v1.SecretKeySelector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeyRef.
func (in *SecretKeyRef) DeepCopy() *SecretKeyRef {
	if in == nil {
		return nil
	}
	out := new(SecretKeyRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecurityConfig) DeepCopyInto(out *SecurityConfig) {
	*out = *in
	if in.RunAsNonRoot != nil {
		in, out := &in.RunAsNonRoot, &out.RunAsNonRoot
		*out = new(bool)
		**out = **in
	}
	if in.RunAsUser != nil {
		in, out := &in.RunAsUser, &out.RunAsUser
		*out = new(int64)
		**out = **in
	}
	if in.FSGroup != nil {
		in, out := &in.FSGroup, &out.FSGroup
		*out = new(int64)
		**out = **in
	}
	if in.SeccompProfile != nil {
		in, out := &in.SeccompProfile, &out.SeccompProfile
		*out = new(v1.SeccompProfile)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecurityConfig.
func (in *SecurityConfig) DeepCopy() *SecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SequencerConfig) DeepCopyInto(out *SequencerConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SequencerConfig.
func (in *SequencerConfig) DeepCopy() *SequencerConfig {
	if in == nil {
		return nil
	}
	out := new(SequencerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SequencerReference) DeepCopyInto(out *SequencerReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SequencerReference.
func (in *SequencerReference) DeepCopy() *SequencerReference {
	if in == nil {
		return nil
	}
	out := new(SequencerReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServiceConfig) DeepCopyInto(out *ServiceConfig) {
	*out = *in
	if in.Annotations != nil {
		in, out := &in.Annotations, &out.Annotations
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Ports != nil {
		in, out := &in.Ports, &out.Ports
		*out = make([]ServicePortConfig, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServiceConfig.
func (in *ServiceConfig) DeepCopy() *ServiceConfig {
	if in == nil {
		return nil
	}
	out := new(ServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ServicePortConfig) DeepCopyInto(out *ServicePortConfig) {
	*out = *in
	out.TargetPort = in.TargetPort
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ServicePortConfig.
func (in *ServicePortConfig) DeepCopy() *ServicePortConfig {
	if in == nil {
		return nil
	}
	out := new(ServicePortConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedConfig) DeepCopyInto(out *SharedConfig) {
	*out = *in
	if in.Logging != nil {
		in, out := &in.Logging, &out.Logging
		*out = new(LoggingConfig)
		**out = **in
	}
	if in.Metrics != nil {
		in, out := &in.Metrics, &out.Metrics
		*out = new(MetricsConfig)
		**out = **in
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = new(ResourceConfig)
		(*in).DeepCopyInto(*out)
	}
	if in.Security != nil {
		in, out := &in.Security, &out.Security
		*out = new(SecurityConfig)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedConfig.
func (in *SharedConfig) DeepCopy() *SharedConfig {
	if in == nil {
		return nil
	}
	out := new(SharedConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StorageConfig) DeepCopyInto(out *StorageConfig) {
	*out = *in
	out.Size = in.Size.DeepCopy()
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StorageConfig.
func (in *StorageConfig) DeepCopy() *StorageConfig {
	if in == nil {
		return nil
	}
	out := new(StorageConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SyncStatusInfo) DeepCopyInto(out *SyncStatusInfo) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SyncStatusInfo.
func (in *SyncStatusInfo) DeepCopy() *SyncStatusInfo {
	if in == nil {
		return nil
	}
	out := new(SyncStatusInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ThrottlingConfig) DeepCopyInto(out *ThrottlingConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ThrottlingConfig.
func (in *ThrottlingConfig) DeepCopy() *ThrottlingConfig {
	if in == nil {
		return nil
	}
	out := new(ThrottlingConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TxPoolConfig) DeepCopyInto(out *TxPoolConfig) {
	*out = *in
	if in.Locals != nil {
		in, out := &in.Locals, &out.Locals
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TxPoolConfig.
func (in *TxPoolConfig) DeepCopy() *TxPoolConfig {
	if in == nil {
		return nil
	}
	out := new(TxPoolConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WSConfig) DeepCopyInto(out *WSConfig) {
	*out = *in
	if in.APIs != nil {
		in, out := &in.APIs, &out.APIs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Origins != nil {
		in, out := &in.Origins, &out.Origins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WSConfig.
func (in *WSConfig) DeepCopy() *WSConfig {
	if in == nil {
		return nil
	}
	out := new(WSConfig)
	in.DeepCopyInto(out)
	return out
}
